# Generated by Django 3.1.6 on 2021-02-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210216_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.FilePathField(path='/img'),
        ),
    ]
